language: go

go:
- '1.15'

sudo: required
services:
- docker

deploy:
- provider: script
  script: bash .travis-deploy.sh
  on:
    branch: master
- provider: script
  script: bash .travis-deploy.sh
  on:
    tags: true
